export const stockData = [
  {
    id: "32342",
    siteId: "---",
    ownername: "Miller Vivian",
    installerName: "Buckridge Stuart",
    applicationStatus: "Submitted for APS Review",
    color: "#eeff41",
  },
  {
    id: "34334",
    siteId: "Enter Enphase Site ID",
    ownername: "Bernier Zachary",
    installerName: "Von Ronaldo",
    applicationStatus: "Approved by APS",
    color: "#91ff35",
  },
  {
    id: "23434",
    siteId: "---",
    ownername: "Murray Alfredo",
    installerName: "Kub Darwin",
    applicationStatus: "Rejected by APS",
    color: "#f44336",
  },
  {
    id: "23434",
    siteId: "32123",
    ownername: "Schinner Leone",
    installerName: "Grant Samir",
    applicationStatus: "Submitted for Enphase Review",
    color: "#eeff41",
  },
  {
    id: "24334	",
    siteId: "32123",
    ownername: "Osinski Elwyn",
    installerName: "Padberg Lacey",
    applicationStatus: "Approved by Enphase",
    color: "#91ff35",
  },
  {
    id: "32342",
    siteId: "Enter Enphase Site ID",
    ownername: "Abernathy Mckenzie",
    installerName: "Turcotte Josie",
    applicationStatus: "Approved by APS",
    color: "#91ff35",
  },
  {
    id: "34323",
    siteId: "32123",
    ownername: "Klocko Albertha",
    installerName: "Tromp Audie",
    applicationStatus: "Rejected by Enphase",
    color: "#f44336",
  },
  {
    id: "32322	",
    siteId: "---",
    ownername: "Terry Ericka",
    installerName: "Boyer Sammie",
    applicationStatus: "Submitted by APS Review",
    color: "#eeff41",
  },

  {
    id: "32342",
    siteId: "Enter Enphase Site ID ",
    ownername: "Roob Leland",
    installerName: "Heidenreich Eldora",
    applicationStatus: "Approved by Enphase",
    color: "#91ff35",
  },
  {
    id: "32123",
    siteId: "32123",
    ownername: "Jerde Frederic	",
    installerName: "Reichel Kim",
    applicationStatus: "Submitted for Enphase Review",
    color: "#eeff41",
  },
];
